const SYM_USAGE   = Symbol("@CMD_USAGE")
const SYM_DESC    = Symbol("@CMD_DESC")
const SYM_EPILOG  = Symbol("@CMD_EPILOG")
const SYM_VERSION = Symbol("@CMD_VERSION")
const SYM_AUTOHELP = Symbol("@CMD_AUTOHELP")
const SYM_SUB     = Symbol("@CMD_SUB")
const SYM_TEST    = Symbol("@ARG_TEST")
const SYM_STREAM  = Symbol("@ARG_STREAM")

const SYM_ALLOW   = Symbol("@ALLOW_EXTRA")
const SYM_ARG_GROUP = Symbol("@ARG_GROUP")

const SYM_ARGREL_DEPENDS     = Symbol("@ARGREL_DEPENDS")
const SYM_ARGREL_CONFLICTS   = Symbol("@ARGREL_CONFLICTS")
const SYM_ARGREL_ATMOSTONE   = Symbol("@ARGREL_ATMOSTONE")
const SYM_ARGREL_ATLEASTONE  = Symbol("@ARGREL_ATLEASTONE")
const SYM_ARGREL_ONLYONE     = Symbol("@ARGREL_ONLYONE")
const SYM_ARGREL_ALLORNONE   = Symbol("@ARGREL_ALLORNONE")

const SYM_REQ     = Symbol("@ARG_REQ")
const SYM_OPT     = Symbol("@ARG_OPT")
const SYM_FLAG    = Symbol("@ARG_FLAG")
const SYM_COUNT   = Symbol("@ARG_COUNT")
const SYM_MULTI   = Symbol("@ARG_MULTI")

const SYM_POS_REQ = Symbol("@POS_REQ")
const SYM_POS_OPT = Symbol("@POS_OPT")
const SYM_POS_RST = Symbol("@POS_REST")
